### ISSUE TITLE
ENABLE_PRECOMPILED_HEADER

### ISSUE THREAD

**Issue by mgalimullin** [piponazo/conan-opencv#3]
Hello! 
Can you add option for ENABLE_PRECOMPILED_HEADER?

**Comment by piponazo** [comment]
Hi @mgalimullin, sure I will add it ;)

**Comment by mgalimullin** [comment]
Hooray! Thank you!

**Comment by piponazo** [comment]
The new option is added, and I am also fixing few other things in the recipe. Let me know if you have any other request ;)

**Comment by mgalimullin** [comment]
I can not download. I see you updated the version to 3.3.0. 
I use "OpenCV/3.3.0@piponazo/testing" in conanfile.txt.
Output of "conan search OpenCV/* -r=conan-transit"
```
Existing package recipes:

OpenCV/2.4.13@masaeedu/stable
OpenCV/2.4.13@memsharded/testing
OpenCV/3.1.0@oslh/stable
OpenCV/3.1.0-0@Brunni/testing
OpenCV/3.1.0-0@piponazo/testing
OpenCV/3.2.0@fmiguelgarcia/stable
OpenCV/3.2.0@ohhi/stable
OpenCV/3.2.0@xmar/stable

```

**Comment by piponazo** [comment]
Take into account that the new recipe is not anymore in the **conan-transit** remote, but in my personal bintray server:
https://bintray.com/piponazo/piponazo

Things have changed a lot in the last months, and the conan-transit repo is now read-only.

**Comment by mgalimullin** [comment]
Thank you!
Is it right command?
`conan remote add piponazo https://bintray.com/piponazo/piponazo`

**Comment by piponazo** [comment]
From the link I sent you before there is a blue button "Set me up!" and there you can find the right command to use:

```
conan remote add <REMOTE> https://api.bintray.com/conan/piponazo/piponazo 
```
;)

**Comment by mgalimullin** [comment]
Ok!
I did it! Everything is working!
